### ISSUE TITLE
Animal Details Page has bottom "padding"

### ISSUE THREAD

**Issue by jiri-kralovec-eal** [F3n-r1r/Givskud-Xamarin-App#4]
There is a big amount of space under bottom paragraphs on the page. These appear to be part of listview but it's not possible to scroll the page by clicking on them.

**Comment by F3n-r1r** [comment]
XAML has to be refactored because "ListView" cannot be nested inside a "ScrollView", because "ListView" has it's own scroll and will therefore break, and display the gap at the bottom.
Suggested Fixes: Use something else than "ListView" or find a way to move "ListView" outside "ScrollView" while still being able to scroll whole page instead of only the "ListView"
